name: Code Quality

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
      - develop

jobs:
  cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-suffix: uv-${{ runner.os }}-${{ matrix.python-version }}

      - name: Install dependecies
        run: uv sync --all-groups

  ruff:
    needs: cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-suffix: uv-${{ runner.os }}-${{ matrix.python-version }}

      - name: Install dependecies
        run: uv sync --all-groups

      - name: Run ruff
        run: |
          uv run ruff check .

  mypy:
    needs: cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-suffix: uv-${{ runner.os }}-${{ matrix.python-version }}

      - name: Install dependecies
        run: uv sync --all-groups

      - name: Run mypy
        run: |
          uv run mypy --strict .
